negotiate-enable:
    path:       /enable
    defaults:   { _controller: 'SimpleSAML\Module\negotiate\Controller\Negotiate::enable' }
negotiate-disable:
    path:       /disable
    defaults:   { _controller: 'SimpleSAML\Module\negotiate\Controller\Negotiate::disable' }
negotiate-retry:
    path:       /retry/{authState}
    defaults:   { _controller: 'SimpleSAML\Module\negotiate\Controller\Negotiate::retry'}
negotiate-backend:
    path:       /backend/{authState}
    defaults:   { _controller: 'SimpleSAML\Module\negotiate\Controller\Negotiate::backend'}
